### ISSUE TITLE
Unexpected usage of GetStartViewModelType

### ISSUE THREAD

**Issue by sdebruyn** [MugenMvvmToolkit/MugenMvvmToolkit#34]
This issue description below is based on my understanding of how Mugen MVVM Toolkit works and how I've been using it. Please correct me if I'm wrong :)

The method `GetStartViewModelType()` in `IMvvmApplication` should return the type of the viewmodel with which the app should start. However, there could be some logic involved:

E.g. the user was already logged in, let's open the main viewmodel of our app
E.g. the user has never used the app before, let's guide him through an onboarding flow

To facilitate this logic, we use the `ServiceProvider` or `IocContainer` in the `MvvmApplication` base class. So we expect these properties to be available and fully initialized.

This is not the case if you use a bootstrapper based on `BootstrapperBase`. The `BootstrapperBase` also uses this method to get the assembly which contains the viewmodels. At that point, you can get an exception because the properties (`IocContainer`) in the `MvvmApplication` aren't initialized.

At the moment you can workaround this by overriding some other methods in `MvvmApplication`, but I suppose that isn't how it's meant to be.

Could this flow be looked at for the next version of Mugen MVVM Toolkit?

The line which I'm talking about: https://github.com/MugenMvvmToolkit/MugenMvvmToolkit/blob/45ce80ec17149bbaa0f2da75d63c381d2d15331c/Core/MugenMvvmToolkit.Core(NetStandard)/Infrastructure/BootstrapperBase.cs#L121

**Comment by Alexx999** [comment]
@SamuelDebruyn I faced the same issue and applied very simple workaround:

```csharp

        public override Type GetStartViewModelType()
        {
            var storage = IocContainer?.Get<ISecureStorageService>();
            if (storage?.IsRegistered() == true)
            {
                return typeof(LoginViewModel);
            }
            return typeof(RegisterViewModel);
        }
```
Basically it will always return RegisterViewModel for assembly init, but when app actually starts it can switch to LoginViewModel - that works perfectly fine.

**Comment by vyacheslav-volkov** [comment]
Hi there,
By design you should use the `GetStartViewModelType` method if you have simple initialization logic, but if you want customize startup view model you should use the `MvvmApplication.StartInternal` method https://github.com/MugenMvvmToolkit/MugenMvvmToolkit/blob/master/Core/MugenMvvmToolkit.Core(NetStandard)/MvvmApplication.cs#L83-L90.
All initialization logic should be in the modules or after you call `MvvmApplication.Initialize` method, `Bootstrapper` should be used only to start `MvvmApplication`, it should not contain any view model startup logic but you can use the `MvvmApplication.Context` property https://github.com/MugenMvvmToolkit/MugenMvvmToolkit/blob/master/Core/MugenMvvmToolkit.Core(NetStandard)/MvvmApplication.cs#L75 to set any startup hints and then use it in the `MvvmApplication.StartInternal` method. 
Is it clear? :)

**Comment by sdebruyn** [comment]
@Alexx999 Thanks, probably simplest workaround :)

@vvs0205 It's the base bootstrapper that calls `GetStartViewModel()`. You said that it shouldn't contain any startup logic, so it should be modified to use something else to determine the assemblies?

**Comment by vyacheslav-volkov** [comment]
@SamuelDebruyn I used it as hint to get more assemblies, you can ignore it and return any type if you will use the `MvvmApplication.StartInternal` method.
