### ISSUE TITLE
[winform] How do I bind to the Items and SelectedItem properties?

### ISSUE THREAD

**Issue by Thraka** [MugenMvvmToolkit/MugenMvvmToolkit#38]
My viewmodel has this:

```csharp
public IList<SadConsole.FontMaster> Fonts => SadConsole.Global.Fonts.Values.ToArray();
```

My view has this:

```csharp
set.Bind(lstFonts, "Items").To(() => (vm, ctx) => vm.Fonts);
```

But there are not any items in the list box. What am I doing wrong?

Thanks!

**Comment by vyacheslav-volkov** [comment]
You need to use ItemsSource property or just empty bind because by default ComboBox uses ItemsSource property, you can find more attached events in this file:
https://github.com/MugenMvvmToolkit/MugenMvvmToolkit/blob/master/Platforms/MugenMvvmToolkit.WinForms(4.5)/Binding/AttachedMembersRegistration.cs#L159-L167

```csharp
set.Bind(lstFonts, AttachedMembers.Object.ItemsSource).To(() => (vm, ctx) => vm.Fonts);
```
