### ISSUE TITLE
MvvmCross comparison

### ISSUE THREAD

**Issue by stefandevo** [MugenMvvmToolkit/MugenMvvmToolkit#5]
Maybe a though question, but how, in your opinion, does this library compare to MvvmCross? What are the benefits you see over MvvmCross? Thanks for your opinion.

**Comment by vyacheslav-volkov** [comment]
Architecturally they are two different projects that solve the same problem. 
Here's a list of the main differences that I know:
- You can pass any navigation parameters because you work directly with a view model.

MvvmCross:

```
Navigate<DetailViewModel>(new DetailParameters() { Index = 2 });
```

MugenMvvmToolkit:

```
using (var editorVm = GetViewModel<ProductEditorViewModel>())            
{
   var productModel = new ProductModel { Id = Guid.NewGuid() };
   editorVm.InitializeEntity(productModel, true);
   if (!await editorVm.ShowAsync())
       return;
   //Code that will be called after the completion of navigation, and yes, this code will be executed even if the application had been tombstoned and then restored.
}
```
- Navigation system works with view models and allows to expect the completion of the operation. This means that you can use the await keyword to wait when the view model is closed, see the example above.
- Navigation system uses the [INavigableViewModel](https://github.com/MugenMvvmToolkit/MugenMvvmToolkit/blob/master/Core/MugenMvvmToolkit.Core%28PCL_WinRT%29/Interfaces/ViewModels/INavigableViewModel.cs) interface to notify about navigation.
- Supports state preservation and restoration for mobile platforms. All you need to do is implement the [IHasState](https://github.com/MugenMvvmToolkit/MugenMvvmToolkit/blob/master/Core/MugenMvvmToolkit.Core%28PCL_WinRT%29/Interfaces/Models/IHasState.cs) interface, and the framework will call these methods automatically depending on the application lifecycle.
- Full Fragment support for Android, you do not need to worry about activity, fragments, sub-fragments or their state all this makes the framework. As far as I know, the MvvmCross has a problem with processing fragments. In this framework, this is no problem.
- Supports bindings for Menu and ActionBar (Android). The MvvmCross does not support it.
- Supports bindings on all platforms, binding supports C# language expressions like Linq, Extension methods, method call, ternary operator (?:), coalescing operator (??), null conditional operator (?.) etc.
  `(Text Items.First(x => x == Name).Value), (Text $string.Format('{0} {1}', Prop1, Prop2))`
- Supports subscription to any control event using binding and pass EventArgs parameter.
  `(TextChanged ViewModelMethod($args)), (DoubleClick Command)`.
- Built-in support for validation. The MvvmCross does not support it.
  `(Text Prop1, Validate=True), (Text $GetErrors(Prop1).FirstOrDefault())`
- Binding supports RelativeSource, ElementName and other macros.
  `(Text $Rel(Window).Title), (Text $El(ElementNameToFind).Title), (Text $self.Tag)`
- Binding supports static and dynamic resources:

```
BindingServiceProvider.ResourceResolver.AddObject("ResourceName", "Value");

(Text $ResourceName.Length)
```
- Supports attached members (properties, events, methods), you can extend any object as you want.
- Work 3 times faster than the WPF bindings on my laptop.

**Comment by stefandevo** [comment]
Thank you very much for this answer. I'll think I'll give your framework a try!

**Comment by vyacheslav-volkov** [comment]
If you are going to need some help or if you have additional questions, I'll be glad to help.

**Comment by stefandevo** [comment]
Thanks. In the meantime, I'll try to make some fuzz about this framework :-) I notified some newsletters already.

**Comment by vyacheslav-volkov** [comment]
Thanks :) Appreciate the support.

**Comment by stefandevo** [comment]
Next question: how to handle specific UI stuff. I suppose via the IOC container? No specific handling like Renderers or DependencyServices in Xam.Forms, or "Plugins" like MvvmCross?

**Comment by vyacheslav-volkov** [comment]
MugenMvvmToolkit uses the [IModule](https://github.com/MugenMvvmToolkit/MugenMvvmToolkit/blob/master/Core/MugenMvvmToolkit.Core%28PCL_WinRT%29/Interfaces/IModule.cs) interface to handle specific UI stuff. By default, all modules are loaded automatically and within a module you decide whether you want to load it. 
For example we have an interface in PCL library [IRepository](https://github.com/MugenMvvmToolkit/MugenMvvmToolkit.Samples/blob/master/MugenMvvmToolkit.Samples.OrderManagerApp/OrderManager.Portable/Interfaces/IRepository.cs) and each platform has a specific implementation. We use module for each platform to load platform specific implementation: [Android module](https://github.com/MugenMvvmToolkit/MugenMvvmToolkit.Samples/blob/master/MugenMvvmToolkit.Samples.OrderManagerApp/OrderManager.Android/AndroidModule.cs#L43), [iOS module](https://github.com/MugenMvvmToolkit/MugenMvvmToolkit.Samples/blob/master/MugenMvvmToolkit.Samples.OrderManagerApp/OrderManager.Touch/TouchModule.cs#L46).

**Comment by stefandevo** [comment]
OK! Very clear!
